### PR TITLE
Map::layers() doesn't really list ALL layers - added a comment about it

### PR DESCRIPTION
**Pull request by HughHoyland**
Took me a while to realize when I tried to load one especially large map.

I guess layers API needs a bit of improvement, but let's start with a comment.

### CODE REVIEW

**Comment by HughHoyland** [comment]
I see an even bigger problem.

While `Layer<'a>` is supposed to live as long as the `Map`, getting `Layer` out of a `LayerType::Group(GroupLayer)` only gives one a `Layer<'a>` where `'a` is the lifetime of the local copy of `GroupLayer`.

Which means it cannot be passed outside of a function.

It is probably safe to cast... in an unsafe block.

**Comment by aleokdev** [comment]
> I see an even bigger problem.
> 
> While `Layer<'a>` is supposed to live as long as the `Map`, getting `Layer` out of a `LayerType::Group(GroupLayer)` only gives one a `Layer<'a>` where `'a` is the lifetime of the local copy of `GroupLayer`.

This is a bug. I see the problem: `get_layer` returns `Layer<'self>` instead of `Layer<'map> + 'map`. Has happened elsewhere before. Sorry about that, I'll submit a fix ASAP.

**Review by aleokdev — COMMENTED** [review]
Looks good, thanks!
Please also add your changes to the `CHANGELOG.md` file under a new section:
```
## [Unreleased]
### Changed
- Improved documentation on `Map::layers` and `Map::get_layer`. (#306)
```

**Comment by HughHoyland** [comment]
Added the changelog.

**Review by aleokdev — APPROVED** [review]
Thank you!

**Pull request merged**
