### PR TITLE
Implement Copy and Clone for most types

### PR DESCRIPTION
**Pull request by afonso360**
This pull request adds the Copy and Clone traits to the applicable types.

This is mostly for end user convenience.

### CODE REVIEW

**Comment by Connicpu** [comment]
I would definitely like this to be merged, not being able to clone parsed objects is a real bummer for me right now

**Comment by Connicpu** [comment]
Awesome, thanks ^_^

**Comment by mattyhall** [comment]
No worries. Should be on crates now :smile: 

Cheers afonso

**Comment by mattyhall** [comment]
Oh and apologies for not seeing it earlier!

**Pull request merged**
