### PR TITLE
Update SFML

### PR DESCRIPTION
**Pull request by aleokdev**
Update SFML dev dependency for the SFML example

### CODE REVIEW

**Comment by aleokdev** [comment]
Was expecting the CI fail. So the CI works with 0.20.0 because its CSFML package is outdated, however it fails on my system because I have the latest version installed.

**Comment by bjorn** [comment]
> So the CI works with 0.20.0 because its CSFML package is outdated, however it fails on my system because I have the latest version installed.

I guess it's not so important whether we run CI on Ubuntu 22.04 or 24.04, so we could at the same time update it to run on `ubuntu-24.04` (currently in beta) instead of `ubuntu-latest`.

**Comment by aleokdev** [comment]
Where did the `docs` workflow go? It's on the `next` branch, at least when viewed from the GitHub file browser, but I can't find it locally or in this PR

**Comment by bjorn** [comment]
> Where did the `docs` workflow go? It's on the `next` branch, at least when viewed from the GitHub file browser, but I can't find it locally or in this PR

It's because this PR is based on `next` from before `current` was merged into it:

image

(it was added in the "Fix doc links" PR)

**Comment by aleokdev** [comment]
Ah, right, thanks! Okay, I'll rebase just to make sure the `docs` workflow also gets the same treatment (although I don't think it needs it)

**Review by bjorn — APPROVED** [review]

**Pull request merged**
