### PR TITLE
[Hotfix] Implement Copy for InvalidTilesetError

### PR DESCRIPTION
**Pull request by aleokdev**
Not sure how PR passed thru CI, I can't compile because of our `deny(missing_copy_implementations)` lint.

### CODE REVIEW

**Comment by bjorn** [comment]
Why did you need the "Trigger CI" commit?

**Comment by aleokdev** [comment]
> Why did you need the "Trigger CI" commit?

I accidentally based the branch against `current`, and changing to `next` didn't retrigger CI

**Comment by bjorn** [comment]
> I accidentally based the branch against `current`, and changing to `next` didn't retrigger CI

Ah, alright. I think you should remove the commit before I approve the PR though.

**Comment by aleokdev** [comment]
I was going to squash before merging for consistency anyways, but I'll rebase to remove that commit if you want

**Review by bjorn — APPROVED** [review]
Ah, I forgot about squashing after getting used to fast-forward merging on GitLab for a bit...

Anyway, approved then, but don't you want to add a changelog entry? :-)

**Comment by aleokdev** [comment]
> Anyway, approved then, but don't you want to add a changelog entry? :-)

Not really, I remembered this time; This hotfix doesn't affect previously released versions so adding a changelog entry for it wouldn't make much sense

**Pull request merged**
