### PR TITLE
Make compatible with latest version of Rust

### PR DESCRIPTION
**Pull request by Ticki**

### CODE REVIEW

**Comment by sinistersnare** [comment]
Not to sound really snobby, but I'm not sure you have contributed enough to consider yourself an 'author' of this project...

**Comment by Ticki** [comment]
You're right. I shouldn't add myself. It's because I have set up Vim to auto-add myself in Cargo.toml.

**Comment by Ticki** [comment]
It fixed now.

**Comment by mattyhall** [comment]
Thanks

**Pull request merged**
