### PR TITLE
Update `next` branch

### PR DESCRIPTION
**Pull request by aleokdev**

### CODE REVIEW

**Review by bjorn — APPROVED** [review]
Approved, but please don't use GitHub to merge `current` into `next`, since it should be possible to simply fast-forward `next` to `current` given that there is no new work submitted to `next` yet.

**Comment by aleokdev** [comment]
How can I do that if the base branch is protected?

**Comment by bjorn** [comment]
> How can I do that if the base branch is protected?

I wasn't sure so I just tried it. This seems to have worked, and automatically closed this PR as merged:

```
bjorn@thor:~/projects/rs-tiled$ git checkout next
Switched to branch 'next'
Your branch is up to date with 'origin/next'.
bjorn@thor:~/projects/rs-tiled$ git merge current
Updating 6dff214..4f94470
Fast-forward
 CHANGELOG.md          | 42 ++++++++++++++++++++++
 Cargo.toml            |  5 +--
 README.md             | 37 +++++++++++++++++++-
 examples/ggez/map.rs  |  8 ++---
 examples/sfml/main.rs |  9 +++--
 src/image.rs          |  8 +----
 src/layers/mod.rs     | 68 ++++++++++++++++++++++++++++++++++++
 src/map.rs            | 97 +++++++++++++++++++++++++++++++++++++++++++++++++--
 tests/lib.rs          | 45 +++++++-----------------
 9 files changed, 266 insertions(+), 53 deletions(-)
bjorn@thor:~/projects/rs-tiled$ git push
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:mapeditor/rs-tiled.git
   6dff214..4f94470  next -> next
```

I'm not sure exactly why this works. Maybe it is because an approved PR was open, or maybe it is because I'm admin. To be sure we could try it without PR next time the branch can just be fast-forwarded, and next time you try this. :-)

**Comment by aleokdev** [comment]
I tried exactly that yet Github denied my push. Pretty sure it's because you're an admin.

**Pull request merged**
