### PR TITLE
remove parent dir on external templates

### PR DESCRIPTION
**Pull request by Aposhian**
This fixes external template loading. I'm not sure if there is another case that this isn't handling though.

### CODE REVIEW

**Comment by aleokdev** [comment]
That's strange. By the looks of it, base_path should be set to the path of the file being loaded. Is it the directory it is in instead? (Also, tests seem to be failing, so the issue is probably deeper than this.)

**Comment by Aposhian** [comment]
Yeah, so this fix looks like it isn't quite right: yes base_path was being set to the directory, not the path of the map file.

**Comment by Aposhian** [comment]
I think it is occurring because the template parsing function is being called recursively for some reason. One solution could be to only strip to the parent path if the path is actually a file name?

**Comment by aleokdev** [comment]
Could you send a set of files that reproduces the error? I can work on it this evening.

**Comment by Aposhian** [comment]
Yeah this can be reproduced with the tiled maps at https://github.com/Aposhian/bevy-sandbox/tree/tilemap-refactor/assets

**Comment by Aposhian** [comment]
I just pushed a more complete workaround that both supports external templates and object layers. It may still be a symptomatic fix, but it is working for now for me.

**Comment by aleokdev** [comment]
Sorry for the wait! After some investigation, `base_path` can be *both* a file or a directory :) Somehow that got through all the reviews done to the templates PR.

**Comment by aleokdev** [comment]
@Aposhian I'm working on a proper internal fix for all inconsistencies between file/directory paths. Is it okay if we use a modified version of your map without texture files to test against this particular error?

**Comment by Aposhian** [comment]
Of course! The example repo I linked to is MIT licensed, including all of the assets, which I created.

**Comment by aleokdev** [comment]
Fixed in #227. Thanks for your help!

**Pull request closed without merging**
